replicaCount: 1
image:
  repository: itzg/minecraft-server
  tag: latest
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
eula: true
whitelistSecret: minecraft-secrets
blacklistSecret: minecraft-secrets
livenessProbe:
  enabled: true
  tcpSocket:
    port: 25565
  initialDelaySeconds: 60
  periodSeconds: 30
readinessProbe:
  enabled: true
  tcpSocket:
    port: 25565
  initialDelaySeconds: 30
  periodSeconds: 15
